name: analysis_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

# dependency_overrides:
#   flutter_web:
#     git:
#       url: https://github.com/flutter/flutter_web
#       path: packages/flutter_web
#   flutter_web_ui:
#     git:
#       url: https://github.com/flutter/flutter_web
#       path: packages/flutter_web_ui

dependency_overrides:
  flutter_web:
      path: /Users/tonytong/Documents/code/flutter_web/packages/flutter_web
  flutter_web_ui:
      path: /Users/tonytong/Documents/code/flutter_web/packages/flutter_web_ui

flutter_web:
  uses-material-design: true
  assets:
   - data/homepage.json
   
   - images/btn_more.png
   - images/login_logo.png
   - images/user_a.png
   - images/home_user_menu.png
 
  fonts:
    - family: Avenir-Black
      fonts:
        - asset: font/Avenir-Black.ttf
